apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
  type: {{ .Values.backendService.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontendService.type }}